### ISSUE TITLE
1.11 update

### ISSUE THREAD

**Issue by seema84** [St3venAU/ArmorStandTools#11]
[10:06:50 ERROR]: Could not pass event PlayerInteractEvent to ArmorStandTools v2.1.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-
Spigot-d60de0a-54450b7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Sp
igot-d60de0a-54450b7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-
Spigot-d60de0a-54450b7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-
Spigot-d60de0a-54450b7]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.j
ava:231) [spigot-1.11.jar:git-Spigot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:440) [spigot-1.11.
jar:git-Spigot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot-1.11.jar:git-Sp
igot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.jar:g
it-Spigot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.jar:gi
t-Spigot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigo
t-d60de0a-54450b7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-d60de0a-5445
0b7]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spig
ot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spig
ot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spig
ot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Sp
igot-d60de0a-54450b7]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.IllegalArgumentException: Can not set boolean field net.minecraft.server.v1_11_R1.EntityA
rmorStand.bz to java.lang.Integer
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source) [?:1.8.0_102]
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source) [?:1.8.0_102]
        at sun.reflect.UnsafeBooleanFieldAccessorImpl.set(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Field.set(Unknown Source) ~[?:1.8.0_102]
        at com.gmail.St3venAU.plugins.ArmorStandTools.NBT.setSlotsDisabled(NBT.java:64) ~[?:?]
        at com.gmail.St3venAU.plugins.ArmorStandTools.MainListener.spawnArmorStand(MainListener.java:378) ~[?:
?]
        at com.gmail.St3venAU.plugins.ArmorStandTools.MainListener.onPlayerInteract(MainListener.java:322) ~[?
:?]
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-
Spigot-d60de0a-54450b7]
        ... 17 more

**Comment by St3venAU** [comment]
Plugin has now been updated for 1.11
