### ISSUE TITLE
ASTools and PlotSquared 3.1.3

### ISSUE THREAD

**Issue by voigtman** [St3venAU/ArmorStandTools#5]
ASTools appears to have broken with the most recent PlotSquared update. 

 [Server thread/ERROR]: Could not pass event PlayerInteractAtEntityEvent to ArmorStandTools v2.03
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1315) [Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/util/bukkit/BukkitUtil
    at com.gmail.St3venAU.plugins.ArmorStandTools.PlotSquaredHook.checkPermission(PlotSquaredHook.java:34) ~[?:?]
    at com.gmail.St3venAU.plugins.ArmorStandTools.Main.checkBlockPermission(Main.java:190) ~[?:?]
    at com.gmail.St3venAU.plugins.ArmorStandTools.Main.playerHasPermission(Main.java:207) ~[?:?]
    at com.gmail.St3venAU.plugins.ArmorStandTools.MainListener.onPlayerInteractAtEntity(MainListener.java:69) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Creative-1.8.8.jar:git-Spigot-6abac0c-9935adc]
    ... 15 more

**Comment by voigtman** [comment]
..oh.. I just noticed you had an update! I'll try this first.

**Comment by voigtman** [comment]
It's a miracle!  It works!! Sorry for the ticket.
